
# Copyright 2019 Pavel Petrov <itnelo@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT license
# that can be found in the LICENSE file.

ARG GOLANG_VERSION

FROM golang:${GOLANG_VERSION}

ARG DEPLOYMENT_PATH
ARG TIMEZONE

WORKDIR ${DEPLOYMENT_PATH}

COPY . .

# timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone && \
    date

RUN go get -d -v && \
	go mod verify && \
	go mod vendor -v && \
	go build -mod vendor -o /usr/local/bin/app -v

USER www-data

ENTRYPOINT ["app", "-mode=debug", "-port=9595"]
